/* Dane katalogu Zamość Zero Waste.
   RAW: [nazwa, kategorie (spacja), adres, telefon, Google place_id, opis, uwaga]
   Aby dodać zakład, dopisz wiersz do RAW. */
const CATS={
 krawiec:{n:"Krawiectwo",k:"krawiec krawcowa szycie przeróbki skracanie spodnie sukienka suknia kurtka płaszcz zamek błyskawiczny podszewka guzik ubranie odzież"},
 szewc:{n:"Szewc",k:"szewc buty obuwie obcas fleki podeszwa zelówka kozaki zamek torebka skóra klejenie"},
 zegarmistrz:{n:"Zegarmistrz",k:"zegarek zegar bateria pasek bransoleta zegarmistrz mechanizm"},
 agd:{n:"AGD",k:"pralka lodówka zmywarka piekarnik kuchenka mikrofalówka ekspres kawa suszarka agd odkurzacz"},
 rtv:{n:"RTV i elektronika",k:"telewizor tv radio wzmacniacz gramofon głośnik słuchawki magnetofon kino domowe elektronika rtv bluetooth"},
 telefon:{n:"Telefony",k:"telefon smartfon ekran szybka bateria iphone samsung xiaomi gsm głośnik"},
 komputer:{n:"Komputery i konsole",k:"komputer laptop drukarka konsola ps4 ps5 xbox pad kontroler płyta zasilacz"},
 rower:{n:"Rowery",k:"rower dętka opona przerzutka hamulce koło centrowanie rower elektryczny"},
 tapicer:{n:"Tapicerstwo",k:"tapicer kanapa sofa fotel krzesło łóżko zagłówek fotel samochodowy tapicerka obicie"},
 podloga:{n:"Parkiet i podłogi",k:"parkiet podłoga cyklinowanie lakierowanie deski renowacja podłogi"},
 meble:{n:"Renowacja mebli",k:"meble renowacja komoda szafa stół krzesło odnawianie malowanie mebli"},
 bizuteria:{n:"Biżuteria",k:"pierścionek obrączka łańcuszek kolczyki biżuteria złoto srebro jubiler złotnik zmniejszenie"},
 klucze:{n:"Klucze i zamki",k:"klucz klucze zamek kłódka dorabianie kluczyk samochodowy pilot ślusarz ostrzenie noży"},
 narzedzia:{n:"Elektronarzędzia i ogród",k:"wiertarka szlifierka myjka karcher kosiarka piła spalinowa podkaszarka spawarka elektronarzędzia ostrzenie"},
 optyk:{n:"Okulary",k:"okulary oprawki zausznik nosek szkła regulacja optyk"}
};
const P='<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">';
// Kafelki: [id, nazwa, podpis, kategorie, zapytanie do Map Google, ikona]
const ITEMS=[
 ["ubrania","Ubrania","spodnie, sukienka, kurtka",["krawiec"],"krawiec",'<path d="M8 3 3 6l2 4 3-1v12h8V9l3 1 2-4-5-3c-1 2-2 3-4 3s-3-1-4-3z"/>'],
 ["zamek","Zamek błyskawiczny","w kurtce, butach, torebce",["krawiec","szewc"],"krawiec szewc",'<path d="M12 2v14M9 5h3M12 8h3M9 11h3M12 14h3"/><rect x="9.5" y="16" width="5" height="6" rx="2"/>'],
 ["buty","Buty i torebki","obcas, podeszwa, klejenie",["szewc"],"szewc naprawa obuwia",'<path d="M3 17v-7l5 1 3-5h3l1 6 6 2v3z"/><path d="M3 20h18"/>'],
 ["zegarek","Zegarek","bateria, pasek, mechanizm",["zegarmistrz"],"zegarmistrz",'<circle cx="12" cy="12" r="6"/><path d="M12 9v3l2 1M9 6.5 10 2h4l1 4.5M9 17.5l1 4.5h4l1-4.5"/>'],
 ["bizuteria","Biżuteria","pierścionek, łańcuszek, rozmiar",["bizuteria"],"złotnik naprawa biżuterii",'<circle cx="12" cy="15" r="6"/><path d="M9 4h6l-3 4z"/>'],
 ["agd","Pralka, lodówka, zmywarka","i inne sprzęty AGD",["agd"],"naprawa AGD",'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M4 7h16"/><circle cx="12" cy="14" r="4"/>'],
 ["rtv","Telewizor i audio","TV, gramofon, głośnik",["rtv"],"naprawa RTV",'<rect x="3" y="6" width="18" height="12" rx="2"/><path d="M8 21h8M9 3l3 3 3-3"/>'],
 ["telefon","Telefon","ekran, bateria, głośnik",["telefon"],"naprawa telefonów",'<rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/>'],
 ["komputer","Komputer i konsola","laptop, drukarka, pad",["komputer"],"naprawa komputerów",'<rect x="5" y="5" width="14" height="10" rx="1"/><path d="M3 19h18"/>'],
 ["rower","Rower","dętka, przerzutka, hamulce",["rower"],"serwis rowerowy",'<circle cx="6" cy="16" r="3.5"/><circle cx="18" cy="16" r="3.5"/><path d="m6 16 4-7h5l3 7M10 9l3 7H6"/>'],
 ["tapicer","Kanapa, fotel, krzesło","tapicerka meblowa i samochodowa",["tapicer"],"tapicer",'<path d="M5 11V8a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v3"/><rect x="3" y="11" width="18" height="6" rx="2"/><path d="M6 17v3M18 17v3"/>'],
 ["meble","Meble drewniane","komoda, stół, szafa",["meble"],"renowacja mebli",'<rect x="5" y="3" width="14" height="17" rx="1"/><path d="M5 9h14M5 14.5h14M11 6h2M11 11.5h2M11 17h2M7 20v1.5M17 20v1.5"/>'],
 ["podloga","Parkiet i podłoga","cyklinowanie, lakierowanie",["podloga"],"cyklinowanie parkietu",'<path d="M3 6h18M3 12h18M3 18h18M9 6v6M15 12v6M6 18v3M17 3v3"/>'],
 ["klucze","Klucze i zamki","dorabianie, kluczyk do auta",["klucze"],"dorabianie kluczy",'<circle cx="8" cy="12" r="4"/><path d="M12 12h9M18 12v3M21 12v2"/>'],
 ["narzedzia","Elektronarzędzia i kosiarki","wiertarka, myjka, piła",["narzedzia"],"naprawa elektronarzędzi",'<path d="M3 8h11v5H3zM14 9.5h4M18 10.5h3M7 13l-1 7h4l1-7"/>'],
 ["optyk","Okulary","oprawki, zauszniki, noski",["optyk"],"optyk naprawa okularów",'<circle cx="7" cy="14" r="3"/><circle cx="17" cy="14" r="3"/><path d="M10 14h4M4 14l1.5-6M20 14l-1.5-6"/>']
];
// [nazwa, kategorie, adres, telefon, place_id, opis, uwaga]
const RAW=[
["Szybka Przeróbka","krawiec","Szopinek 54D","+48 500 352 159","ChIJhwk2HLsGcyYRLBG3Qr2arKI","Przeróbki odzieży, w tym sukni ślubnych i wizytowych."],
["Igła i nitka – usługi krawieckie","krawiec","ul. Piłsudskiego 6","+48 502 728 308","ChIJ48uFMApnI0cRR8F9VM0tq1g","Skracanie, zwężanie, wszywanie zamków w kurtkach."],
["AGA Pracownia Krawiecka","krawiec","ul. Zamoyskiego 51","+48 790 426 646","ChIJFa0vPg5nI0cRoRzcYD2rcM0","Przeróbki krawieckie, prasowalnia i pralnia."],
["Beata Przerabia","krawiec","ul. Bazyliańska 34","+48 721 436 456","ChIJIw9zqmpnI0cRuyxwcD_-WQk","Przeróbki i poprawki odzieży."],
["Usługi krawieckie Maria Prochowicz","krawiec","ul. Wyszyńskiego 30","+48 692 089 127","ChIJWXbj2g5nI0cRXfBUMI0E7cw","Przeróbki odzieży, szybkie poprawki.","Możliwe, że zakład jest zamknięty"],
["Naprawa obuwia i torebek – Szewc","szewc","ul. Grecka 5","+48 782 001 785","ChIJ3f7WjN1nI0cR5xrsodEvU9c","Klejenie, fleki, wymiana zamków w kozakach, naprawa torebek."],
["Zakład Naprawy Obuwia G. Piskor","szewc","ul. Orzeszkowej 28","+48 512 294 155","ChIJvYgzFbFnI0cRdE7iMSsUfvw","Naprawa obuwia i wyrobów skórzanych, wymiana podeszew.","Dwa adresy w sieci: Orzeszkowej 17 i 28"],
["Usługi szewskie Władysław Brodziński","szewc","ul. Hrubieszowska 34","+48 692 557 841","ChIJK-pTWBBnI0cRGoCXQUC_Hao","Naprawa obuwia."],
["Szewc F.H.U. „TEKS”","szewc","ul. Niepodległości 2","","ChIJVVJHYQBnI0cRZpNq6RwMzNE","Naprawa obuwia."],
["Zegarmistrz – Bazyliańska","zegarmistrz","ul. Bazyliańska 26","+48 504 096 524","ChIJ104Rh2VnI0cR9d8wLuqEDiY","Naprawa zegarków, wymiana baterii i pasków."],
["Zegarmistrz w Hetmanie","zegarmistrz","ul. Piłsudskiego 8","","ChIJd2bQifVnI0cRmIVxjZ8xd9M","Naprawa zegarków, baterie, paski, czyszczenie."],
["Zegarmistrzostwo – Grodzka","zegarmistrz","ul. Grodzka 10","+48 603 205 150","ChIJTVpIbaRnI0cRJrR_yVTu73A","Naprawa zegarków, także trudniejsze mechanizmy."],
["Zakład zegarmistrzowski Andrzej Wójtowicz","zegarmistrz klucze","ul. Hrubieszowska 30A","+48 606 467 834","ChIJPyc0YRBnI0cR7UysfjQ1ICc","Naprawa zegarków, dorabianie kluczy."],
["Kurant – złoto, srebro, zegarki","bizuteria zegarmistrz","ul. Partyzantów 65 (DH Agora)","+48 84 639 31 26","ChIJW3JJvg1nI0cRcLjfpvyR98k","Biżuteria, obrączki na zamówienie, naprawa zegarków."],
["Naprawa AGD Rafał Gdak","agd","Zwódne 46","+48 507 480 027","ChIJ7UmZ-eFnI0cRt9cuJeeKHOE","Naprawa pralek, zmywarek i innego sprzętu AGD."],
["Serwis AGD MEGAN","agd","ul. Partyzantów 34","+48 883 033 003","ChIJq5IUChJnI0cR7z6d4-s9uUs","Pralki, zmywarki, ekspresy. Odbiór sprzętu z domu."],
["Zakład naprawy sprzętu domowego Lucjan Sierkowski","agd","ul. Słoneczna 8","+48 84 638 40 51","ChIJmQrO2nJnI0cRBYErHvaVHqY","Specjalizacja: sprzęt Bosch i Siemens."],
["PW Serwis-Lux – Serwis AGD","agd","ul. Reja 14","+48 502 247 504","ChIJ3cqf9A1nI0cR1we-swzi0ps","Pralki, kuchenki, mikrofalówki, sprzęt do zabudowy."],
["PHU Ryszard Puliński – pralki i lodówki","agd","ul. Żaków 2","+48 84 638 55 36","ChIJZXF97ApnI0cR7qIL7A2CCuI","Naprawa pralek i lodówek."],
["Digital Serwis RTV","rtv","ul. Brzozowa 24/5","+48 796 334 114","ChIJ7wYggBJnI0cRGT5i4fpLB8A","Sprzęt RTV i audio, także sprzęt vintage."],
["Tele-Radio – E. Matczuk","rtv","ul. Wyszyńskiego 34","+48 84 627 64 70","ChIJeRpx8KNnI0cRl9fWlZ0fLLo","Gramofony, wzmacniacze, głośniki Bluetooth, słuchawki."],
["Naprawa sprzętu RTV – Lwowska","rtv agd","ul. Lwowska 6","+48 606 890 588","ChIJDXQnexJnI0cRuGGOwXFGDI4","Sprzęt RTV i drobne AGD, np. odkurzacze."],
["Pal-Color – naprawa telewizorów","rtv","ul. Młyńska 27","+48 602 632 234","ChIJ2yozZm1nI0cRwmseKT1AUg8","Naprawa telewizorów."],
["Elektronika Naprawy – Marek Bajan","rtv komputer","ul. Rzemieślnicza 19 (Skokówka)","+48 604 082 677","ChIJ18DS-31dI0cR-9PZzlkj700","Elektronika samochodowa, CB-radia, laptopy, telewizory."],
["KrissGSM.eu","telefon","ul. Wyszyńskiego 1","+48 531 385 994","ChIJnbtVuodnI0cRlggoBAmopQw","Wymiana szybek, ekranów i baterii w telefonach."],
["MR. SZYBKA GSM","telefon","ul. Lubelska 40/45","+48 799 797 697","ChIJQ_pERftnI0cR1dth-iZWsQ4","Naprawa telefonów, baterie, aparaty, folie."],
["Serwis Telefonów Komórkowych GSM","telefon","ul. Partyzantów 39","+48 788 099 914","ChIJGVxKPwpnI0cRrKP_QWOQcjE","Naprawa telefonów komórkowych."],
["Serwis telefonów telakces","telefon","Galeria Twierdza, ul. Przemysłowa 10","+48 799 777 808","ChIJaQdHqS5nI0cRhyF4LT9PtuA","Serwis telefonów Apple, Samsung, Xiaomi."],
["NOVITECH – serwis laptopów","komputer","ul. Partyzantów 53","+48 502 540 999","ChIJ00A2PwxnI0cRk7KqsLJPZlo","Naprawa laptopów, zasilaczy, padów do konsol."],
["Mawir Komputery – Serwis","komputer","ul. Świętego Piątka 12","+48 84 543 11 11","ChIJNXMxHwdnI0cRECXXaY-UN14","Naprawa komputerów i odzyskiwanie danych."],
["Serwis Konsol i Laptopów","komputer","Sitaniec 392","+48 737 476 096","ChIJU9-NLCBmI0cRs-GKVENlOR4","Czyszczenie i naprawa konsol, pady, laptopy."],
["Soft – Piotr Różycki","komputer","ul. Zamenhofa 12","+48 84 639 10 21","ChIJUdh396RnI0cRlhwkqiWuT6A","Serwis komputerów i drukarek."],
["Biko – Usługi Informatyczne","komputer","ul. Partyzantów 32","+48 451 079 772","ChIJKcxgEApnI0cRHduDV0g4PBw","Naprawa komputerów, wymiana baterii w laptopach."],
["Serwis rowerowy K9","rower","ul. Kopernika 9","+48 535 548 915","ChIJbevyfb1nI0cRK3Yme4STObg","Serwis rowerów, także elektrycznych."],
["Ale Jazda – sklep i serwis rowerowy","rower","ul. Wyszyńskiego 39B","+48 500 191 818","ChIJLTHk8wVnI0cRGL8AsP1mMTw","Serwis rowerowy."],
["Serwis Rowerowy – Partyzantów","rower","ul. Partyzantów 22","+48 791 070 096","ChIJcfLWr6BnI0cRj8l05IdH_AA","Naprawa rowerów, możliwy dojazd do klienta."],
["Atlanta – sklep i serwis rowerowy","rower","ul. Partyzantów 29","+48 84 639 15 29","ChIJP_xqwwtnI0cR2G0M0baGeX0","Serwis rowerów, centrowanie kół."],
["Tapicer Szelug","tapicer","Kalinowice 246A","+48 603 559 393","ChIJ38KIiyNnI0cRgwHnkWVaoMA","Tapicerstwo meblowe i samochodowe."],
["Tapicerstwo samochodowe i meblowe – Kalinowice","tapicer","Kalinowice 122","+48 721 497 193","ChIJ4Rcf_KNnI0cRDZ1f5EdmzeA","Fotele samochodowe, siedzenia motocyklowe, meble."],
["Usługi tapicerskie Jacek Koszuta","tapicer","ul. Szczebrzeska 47A","+48 509 783 083","ChIJNxLX48dnI0cRM-o_q1895LA","Łóżka, krzesła, tapicerka samochodowa."],
["Tapicer Zamość – Zamoyskiego","tapicer","ul. Zamoyskiego 51","+48 724 623 714","ChIJTQYN9zxnI0cRerUjxhE5daM","Tapicerstwo meblowe."],
["Tapicerstwo Leszek Krasoń","tapicer","ul. Kiepury 14","+48 608 632 821","ChIJwz2BsAlnI0cRgUqyQbOkN5U","Kanapy, poduszki, tapicerka samochodowa."],
["Cyklinomania.pl","podloga","ul. Przerwy-Tetmajera 4","+48 500 535 454","ChIJTyxZASRnI0cRBCjfVBSc2RQ","Bezpyłowe cyklinowanie i renowacja parkietu."],
["Perfect Floor – Sitaniec","podloga","Sitaniec-Kolonia 20","+48 534 136 968","ChIJFxNX0n5nI0cR4LWP8niCGOg","Cyklinowanie i lakierowanie parkietu."],
["Perfectfloor – Chyża","podloga","Chyża 120","+48 881 508 815","ChIJlQDc3BBpI0cR3q76XjMxZXc","Cyklinowanie, także naprawa źle wykonanych podłóg."],
["S.K. OdNowa","meble","ul. Kilińskiego 7A","+48 881 500 697","ChIJp6RGGbNnI0cRoU0Qn3DGh3s","Renowacja starych mebli."],
["Zmalowane – stylizacja mebli","meble","ul. Północna 6","+48 519 383 929","ChIJB_pk8XpnI0cRnUh2CdHCv3U","Odnawianie i malowanie mebli."],
["Pracownia Biżuterii Dariusz Królikowski","bizuteria","ul. Pereca 11","+48 84 638 55 35","ChIJNbF6QqRnI0cRO_Ov5IfmXFA","Naprawa i zmiana rozmiaru pierścionków, czyszczenie."],
["Pracownia Złotnicza Dorota Koska","bizuteria","ul. Bazyliańska 16","+48 84 627 19 99","ChIJEyqLEqRnI0cRD0yt5idNExE","Naprawa biżuterii, przetapianie złota."],
["Pracownia złotniczo-jubilerska M. Niderla","bizuteria","ul. Partyzantów 65","","ChIJKRNpqOVnI0cRR32NzupIYWY","Naprawa biżuterii, wyroby na zamówienie."],
["F.H.U. Kluczyk – Robert Gruszka","klucze","ul. Przemysłowa 10","+48 601 805 272","ChIJN70mwLRnI0cRU8MyFQlyg_M","Dorabianie i kodowanie kluczy samochodowych."],
["Klucznik – punkt dorabiania kluczy","klucze","ul. Partyzantów 65","+48 84 639 31 26","ChIJW3JJvg1nI0cR8_MOWJdjmU4","Klucze, kluczyki samochodowe, ostrzenie noży.","Ten sam numer co Kurant – sprawdzić"],
["Dorabianie kluczy Zygmunt Głazowski","klucze","ul. Hrubieszowska 30A","+48 503 747 131","ChIJ4dZxeR-PJEcRyc4IA4-nTJs","Klucze do domu i samochodu."],
["Olikar – dorabianie kluczy, ślusarz","klucze","CH Carrefour, ul. Lwowska 56","+48 602 393 056","ChIJxbFuwhRnI0cRiTXe_LUQS3U","Klucze, piloty samochodowe, skracanie bransolet."],
["Klucznik II – P. Skwarzyński","klucze","ul. Piłsudskiego 8","+48 84 627 06 88","ChIJ0WxmkbNnI0cR4WrGF7e_hWo","Dorabianie kluczy, klucze z immobilizerem."],
["ALserwis – elektronarzędzia i myjki","narzedzia","Szopinek 89e","+48 731 095 218","ChIJcyJYR69nI0cROdA3v7JfX3U","Naprawa elektronarzędzi i myjek ciśnieniowych."],
["WENC – serwis elektronarzędzi i sprzętu spalinowego","narzedzia","Stary Zamość 13A","+48 503 874 028","ChIJzwfK_ZJuI0cRmSVXPu6iGiw","Piły, kosiarki, podkaszarki."],
["PNEU-MIG Andrzej Szykuła","narzedzia","ul. Graniczna 40","+48 608 089 488","ChIJ1WdA5pVnI0cRI9pRFGE7glM","Naprawa spawarek i urządzeń warsztatowych."],
["Farbacol – Centrum Elektronarzędzi","narzedzia","ul. Dzieci Zamojszczyzny 2","+48 669 998 921","ChIJ0VVffKhnI0cRHzG7y09ilD0","Sklep z serwisem elektronarzędzi."],
["Ostrzenie narzędzi – Lwowska","narzedzia klucze","ul. Lwowska 36","","ChIJGY9ZDBNnI0cRh93JPGPFLsk","Ostrzenie narzędzi."],
["Okularium – salon optyczny","optyk","ul. Reja 21","+48 84 627 53 72","ChIJFa0vPg5nI0cRsSIZjykriZo","Regulacja i drobne naprawy okularów."],
["Optyk Grodzka – Anna Mączka-Kulik","optyk","ul. Grodzka 5","+48 786 166 444","ChIJz9t2EqRnI0cRYHn5A7aXVBM","Naprawa okularów, także przeciwsłonecznych."],
["Bryle Optyk Express","optyk","Revia Park, ul. Lubelska 40","+48 518 222 961","ChIJ9eM8lHJnI0cRmSMO8iVZIL0","Okulary, naprawy oprawek."]
];
// Drugie pytanie: [etykieta, rdzenie słów szukane w nazwie i opisie zakładu]
const SUBS={
 ubrania:[["Skrócić albo zwęzić","skrac zwez przerob"],["Suknia ślubna lub wizytowa","sukni slub wizyt"],["Podszewka, rękawy, kaptur","podszew"],["Drobne poprawki","poprawk"]],
 zamek:[["W kurtce lub spodniach","kurtk zamk"],["W butach i kozakach","kozak obuw"],["W torebce","torebk"]],
 buty:[["Obcas i fleki","flek obcas"],["Podeszwa","podeszw"],["Coś się odkleiło","klejen"],["Torebka lub inna skóra","torebk skor"]],
 zegarek:[["Bateria","bateri"],["Pasek lub bransoleta","pask bransol"],["Stoi, choć ma baterię","mechaniz"]],
 bizuteria:[["Rozmiar pierścionka","rozmiar pierscion"],["Zerwany łańcuszek, zapięcie","napraw"],["Obrączki z rodzinnego złota","przetap zlot obracz"]],
 agd:[["Pralka","pralk"],["Lodówka","lodow"],["Zmywarka","zmywar"],["Ekspres do kawy","ekspres"],["Kuchenka, piekarnik, mikrofalówka","kuchen mikrofal"],["Odkurzacz","odkurz"],["Sprzęt Bosch lub Siemens","bosch siemens"]],
 rtv:[["Telewizor","telewizor"],["Gramofon, wzmacniacz, magnetofon","gramofon wzmacniacz vintage"],["Głośnik lub słuchawki","glosnik sluchawk"]],
 telefon:[["Ekran lub szybka","szyb ekran"],["Bateria","bateri"],["Aparat lub głośnik","aparat"]],
 komputer:[["Laptop","laptop"],["Drukarka","drukar"],["Konsola lub pad","konsol pad"],["Odzyskanie danych","danych"]],
 rower:[["Przegląd i drobne naprawy","serwis"],["Rower elektryczny","elektrycz"],["Krzywe koło","kol centrow"],["Utknąłem z rowerem, potrzebny dojazd","dojazd"]],
 tapicer:[["Kanapa lub fotel","kanap mebl"],["Krzesła lub łóżko","krzes lozk"],["Fotel samochodowy","samochod"]],
 meble:[["Odnowienie starego mebla","renowac"],["Przemalowanie","malowan"]],
 podloga:[["Cyklinowanie","cyklin"],["Lakierowanie","lakier"],["Poprawka po złym cyklinowaniu","zle"]],
 klucze:[["Klucz do domu","dom"],["Kluczyk lub pilot do auta","samochod pilot immobil"],["Ostrzenie noży","ostrz"]],
 narzedzia:[["Wiertarka, szlifierka","elektronarz"],["Myjka ciśnieniowa","myj"],["Kosiarka, piła, podkaszarka","kosiar pil"],["Spawarka","spawar"]],
 optyk:[["Oprawki","oprawk"],["Okulary przeciwsłoneczne","przeciwslon"],["Regulacja, luźny zausznik","regulac"]]
};
// Porady: why = dlaczego warto, diy = zrób to sam, ask = o co zapytać fachowca
const TIPS={
 ubrania:{why:"Dobrze skrojona kurtka czy płaszcz po wymianie zamka lub podszewki posłuży kolejne lata.",diy:["Przyszywając guzik, zostaw pod nim kilka milimetrów luzu z nici. Wtedy nie urwie się przy zapinaniu.","Małą dziurę przy szwie zszyj od razu, zanim się powiększy."],ask:["Czy potrzebna jest przymiarka?","Kiedy rzecz będzie gotowa do odbioru?"]},
 zamek:{why:"Często wystarczy wymienić sam suwak, a nie cały zamek.",diy:["Zacinający się suwak natrzyj grafitem z ołówka, mydłem albo świecą.","Nie szarp na siłę, bo wyrwiesz ząbki."],ask:["Czy wystarczy wymiana suwaka, czy trzeba wszyć nowy zamek?","Czy zakład ma zamek w podobnym kolorze?"]},
 buty:{why:"Skórzane buty można podzelować i naprawiać wiele razy.",diy:["Mokre buty susz z dala od kaloryfera, wypchane papierem.","Regularnie impregnuj skórę i zamsz."],ask:["Czy wymienić fleki teraz, zanim zniszczy się obcas?","Czy podeszwę da się podkleić, czy trzeba ją wymienić?"]},
 zegarek:{why:"Wymiana baterii czy paska to zwykle szybka usługa, a dobry zegarek może działać dziesiątki lat.",diy:["Zegarek kwarcowy, który stanął, najczęściej potrzebuje tylko nowej baterii."],ask:["Jeśli zegarek jest wodoszczelny, poproś o sprawdzenie uszczelki przy wymianie baterii."]},
 bizuteria:{why:"Złotnik zmniejszy lub powiększy pierścionek, a ze starego złota wykona nową biżuterię.",diy:["Srebro czyść miękką ściereczką do srebra, bez past ściernych."],ask:["Czy można przetopić własne złoto?","Ile potrwa zmiana rozmiaru?"]},
 agd:{why:"Wiele awarii AGD to wymiana jednej części, np. pompy, grzałki albo uszczelki.",diy:["Zawsze najpierw odłącz urządzenie od prądu i wody.","Pralka nie odpompowuje wody? Sprawdź filtr pompy, zwykle z przodu na dole. Podstaw miskę i ręcznik.","Zmywarka źle myje? Wyczyść filtr na dnie i sprawdź, czy ramiona się obracają.","Nie otwieraj obudowy samodzielnie."],ask:["Spisz model i numer z tabliczki znamionowej, zanim zadzwonisz.","Ile kosztuje dojazd i diagnoza?"]},
 rtv:{why:"Stary sprzęt audio często jest solidniejszy od nowego i da się go naprawić.",diy:["Sprawdź kabel zasilający, gniazdko i baterie w pilocie.","Nie otwieraj obudowy. W środku mogą być naładowane elementy."],ask:["Podaj model urządzenia przez telefon.","Czy zakład robi bezpłatną wycenę?"]},
 telefon:{why:"Wymiana ekranu lub baterii zwykle kosztuje ułamek ceny nowego telefonu.",diy:["Telefon nie ładuje? Delikatnie wyczyść gniazdo drewnianą wykałaczką.","Przed oddaniem do serwisu zrób kopię zdjęć i kontaktów.","Spuchnięta bateria: nie ładuj telefonu i oddaj go do serwisu jak najszybciej."],ask:["Czy części są oryginalne czy zamienniki?","Czy naprawa ma gwarancję?"]},
 komputer:{why:"Wolny lub przegrzewający się laptop często potrzebuje tylko czyszczenia albo nowego dysku.",diy:["Zrób kopię ważnych plików, zanim oddasz sprzęt.","Nie zasłaniaj kratek wentylacyjnych, np. kocem czy poduszką."],ask:["Czy diagnoza jest płatna?","Czy zakład poinformuje o kosztach przed naprawą?"]},
 rower:{why:"Regularny przegląd kosztuje mniej niż wymiana zniszczonego napędu.",diy:["Smaruj łańcuch co kilkaset kilometrów i po jeździe w deszczu.","Pompuj opony do ciśnienia podanego na ich boku."],ask:["Czy warto zrobić przegląd przed sezonem?","Czy serwis naprawia rowery elektryczne?"]},
 tapicer:{why:"Stara kanapa czy fotel z solidną ramą po nowym obiciu często jest lepszy od nowego mebla.",diy:["Zdejmowane pokrowce pierz zgodnie z metką, zanim zabrudzenia się utrwalą."],ask:["Jakie materiały są do wyboru?","Czy zakład odbiera i odwozi meble?"]},
 meble:{why:"Lite drewno można odnawiać wiele razy.",diy:["Chwiejące się krzesło: dokręć śruby albo podklej połączenia klejem do drewna.","Drobne rysy zamaskujesz woskiem lub kredką do mebli."],ask:["Czy mebel jest z litego drewna, czy oklejony?","Ile potrwa renowacja?"]},
 podloga:{why:"Parkiet z litego drewna można cyklinować kilka razy, zamiast kłaść nową podłogę.",diy:["Przyklej filcowe podkładki pod nogi krzeseł i stołów."],ask:["Czy cyklinowanie jest bezpyłowe?","Ile razy można jeszcze cyklinować te deski?"]},
 klucze:{why:"Dorobienie kluczyka lub pilota jest zwykle dużo tańsze niż wymiana zamka.",diy:["Zacinający się zamek posmaruj smarem do zamków lub grafitem, nie olejem."],ask:["Jakie dokumenty są potrzebne do dorobienia kluczyka samochodowego?"]},
 narzedzia:{why:"W elektronarzędziach często zużywają się tanie części, np. szczotki węglowe.",diy:["Myjka traci ciśnienie? Sprawdź filtr na wejściu wody.","Kosiarkę przed sezonem: wyczyść filtr powietrza i zalej świeże paliwo."],ask:["Czy części do tego modelu są dostępne?"]},
 optyk:{why:"Luźny zausznik czy krzywe oprawki to zwykle kilka minut pracy.",diy:["Szkła czyść płynem i ściereczką z mikrofibry, nie koszulką."],ask:["Wiele salonów reguluje okulary za darmo. Zapytaj, nawet jeśli kupiłeś je gdzie indziej."]}
};

